---
title: "Inferring BD rates on truncated PBD trees with RPANDA"
output: html_notebook
---

Load the most recent github version of RPANDA.

```{r}
#devtools::install_github("hmorlon/PANDA", dependencies = TRUE)
library(RPANDA)
library(ape)
library(phytools)
```

# Provided example on Cetaceans

```{r fig.width=10, fig.asp=1.5}
data(Cetacea)

plot(Cetacea) ; axisPhylo()
tot_time<-max(node.age(Cetacea)$ages)

# slice the Cetaceae tree 10 Myr ago:
time_stop=10
sliced_tree <- Cetacea
sliced_sub_trees <- treeSlice(sliced_tree,slice = tot_time-time_stop, trivial=TRUE)

for (i in 1:length(sliced_sub_trees)){if (Ntip(sliced_sub_trees[[i]])>1){
  sliced_tree <- drop.tip(sliced_tree,tip=sliced_sub_trees[[i]]$tip.label[2:Ntip(sliced_sub_trees[[i]])])
}}

for (i in which(node.depth.edgelength(sliced_tree)>(tot_time-time_stop))){sliced_tree$edge.length[which(sliced_tree$edge[,2]==i)] <- sliced_tree$edge.length[which(sliced_tree$edge[,2]==i)]-time_stop}

plot(sliced_tree) ; axisPhylo()
```

```{r}
Ntip(sliced_tree) # 27 lineages present 10 Myr have survived until today
```

Now we can fit birth-death models excluding the 10 last Myr

```{r}
# Fit the pure birth model (no extinction) with a constant speciation rate

f.lamb <-function(t,y){y[1]}
f.mu<-function(t,y){y[1]}
lamb_par<-c(0.09)
mu_par<-c(0.05)

result_cst <- fit_bd_in_past(sliced_tree, tot_time, time_stop, f.lamb, f.mu, 
                             desc=Ntip(Cetacea), tot_desc=89, lamb_par, mu_par, dt=1e-3)
result_cst
```

# Similar analysis on simulated PBD trees

```{r}
pars_df <- read.csv("../simulations_output/1-PBD/all_simulations_inference.csv")

par_row <- 5084
#par_row <- 5050
pars <- pars_df[par_row,]
pars[c("param_vary", "i_param_var", "replicate")]
```

```{r fig.width=10, fig.asp=1.0}
param_vary <- pars_i$param_vary
i_param_var <- pars_i$i_param_var
replic <- pars_i$replicate
PBD_tree <- read.tree(paste0("../simulations_output/1-PBD/trees/stree_random-par",param_vary,"-var",i_param_var,"-rep",replic,".nwk"))
plot(PBD_tree, root.edge = TRUE, cex = 0.5) ; axisPhylo()
```

```{r fig.width=10, fig.asp=1.0}
tot_time <- max(node.age(PBD_tree)$ages)

# slice the tree 2 Myr ago:
time_stop=2

slice_tree <- function(tree, time_stop){
  sliced_tree <- tree
  sliced_sub_trees <- treeSlice(sliced_tree,slice = tot_time-time_stop, trivial=TRUE)
  
  for (i in 1:length(sliced_sub_trees)){
    if (Ntip(sliced_sub_trees[[i]])>1){
      sliced_tree <- drop.tip(sliced_tree,tip=sliced_sub_trees[[i]]$tip.label[2:Ntip(sliced_sub_trees[[i]])])
    }
  }
  
  for (i in which(node.depth.edgelength(sliced_tree)>(tot_time-time_stop))){
    sliced_tree$edge.length[which(sliced_tree$edge[,2]==i)] <- sliced_tree$edge.length[which(sliced_tree$edge[,2]==i)]-time_stop
  }
  return(sliced_tree)
}

sliced_tree <- slice_tree(PBD_tree, time_stop)

plot(sliced_tree, cex=0.8) ; axisPhylo()
```

```{r}
equivalent_bd_rates <- function(param) {
  l1 <- param[1]
  l2 <- param[2]
  l3 <- param[3]
  m1 <- param[4]
  m2 <- param[5]
  p <- 0.5*(l2+l3+m2)/l3 * (1-sqrt(1-4*l3*m2/((l2+l3+m2)^2)))
  l <- (1-p)*l1
  m <- m1
  rates <- c(l, m)
  names(rates) <- NULL
  rates
}

eq_BD <- equivalent_bd_rates(pars[c("PBD.l1", "PBD.l2", "PBD.l3", "PBD.mu1", "PBD.mu2")])
eq_BD
```

```{r}
# Fit the constant-rate birth-death model
f.lamb <-function(t,y){y[1]}
f.mu<-function(t,y){y[1]}
lamb_par<-c(0.5)
mu_par<-c(0.2)

fit_full <- fit_bd(PBD_tree, tot_time, f.lamb, f.mu, lamb_par, mu_par)

split_times <- 1:5
fits_truncated <- sapply(split_times, function(time_stop){
  sliced_tree <- slice_tree(PBD_tree, time_stop)
  result_cst <- fit_bd_in_past(sliced_tree, tot_time, time_stop, f.lamb, f.mu, 
                               desc=Ntip(PBD_tree), tot_desc=Ntip(PBD_tree), lamb_par, mu_par, dt=1e-3)
  result_cst
})

rbind(split_times=c(NA,0,split_times), 
      cbind(c("equiv. BD", unlist(eq_BD)), 
            fit_full[c("model", "lamb_par", "mu_par")], 
            fits_truncated[c("model", "lamb_par", "mu_par"),]))
```






