---
title: "Compare constant-PBD simulated trees with the corresponding variable-BD simulated trees"
output: html_notebook
---

```{r}
library(reticulate)
library(TreeSim)
library(R.utils)
library(geiger)
library(treestats)
library(ape)
```

# Load time-varying DB rates

```{r}
np <- import("numpy")
full_results <- np$load("shape_sim_varBD_trees/variable_BDrates.npy", allow_pickle=T)
#params <- data.frame(apply(full_results[,5:9], 2, as.numeric))
#names(params) <- c("l1","l2","l3","m1","m2")
#params
full_results[[1]]
```

```{r}
BD_rtt <- full_results
plot(full_results[[1]]$birth_rate)
plot(full_results[[1]]$death_rate)
```

# Piecewise-constant simulations

```{r}
sim_tree <- function(RTT){
  tree <- withTimeout(sim.bdsky.stt(n           = 0, 
                                    timestop    = age, 
                                    lambdasky   = rev(RTT$birth_rate[-1]), 
                                    deathsky    = rev(RTT$death_rate[-1]), 
                                    timesky     = c(0, seq(0.01, age, length.out=200)[2:199]), 
                                    sampprobsky = rep(0,199), 
                                    rho         = 1), timeout = 10.0, onTimeout = "warning")
  if (is.numeric(tree) && tree == age){
    branch <- list(edge =  matrix(c(2, 1), ncol = 2), edge.length = age, tip.label = "t1", Nnode = 1, root.edge = 0)
    class(branch) <- "phylo"
    return(branch)
  }
  
  return(tree[[1]])
}

age=15
n_trees=200
sim_BDtrees <- lapply(full_results, function(RTT)lapply(1:n_trees, function(i){
  i <- 0
  while (i<100){
    #print(paste("i=", i))
    tree_left <- sim_tree(RTT)
    if (is.phylo(tree_left)){
      tree_right <- sim_tree(RTT)
      if (is.phylo(tree_right)){
        return(bind.tree(tree_left, tree_right, position=tree_left$root.edge))
      }
    }
    i <- i+1
  }
  return(-1)
}))
```

```{r message=FALSE}
sim_BDtrees_summary <- summary(sapply(sim_BDtrees, sapply, function(x)ifelse(is.phylo(x), is.binary.tree(x), NA)))
sim_BDtrees_summary

make.binary <- function(tree){
  while (!is.binary.tree(tree)){
    i_max_1 <- which.max(tree$edge[,1])
    i_max_2 <- which.max(tree$edge[,2])
    tree$edge <- cbind(tree$edge[-i_max_1,1], tree$edge[-i_max_2,2])
    tree$Nnode <- tree$Nnode - 1
    len = length(tree$edge.length)
    if (i_max_2==1){
      tree$edge.length <- c(tree$edge.length[1]+tree$edge.length[2], tree$edge.length[3:len])
    }else if (i_max_2 == len-1){
      tree$edge.length <- c(tree$edge.length[1:(i_max_2-1)], tree$edge.length[i_max_2]+tree$edge.length[i_max_2+1])
    }else{
      tree$edge.length <- c(tree$edge.length[1:(i_max_2-1)], tree$edge.length[i_max_2]+tree$edge.length[i_max_2+1], tree$edge.length[(i_max_2+2):length(tree$edge.length)])
    }
  }
  return(tree)
}
sim_BDtrees_binary <- lapply(sim_BDtrees, lapply, function(x)if(is.phylo(x)){make.binary(x)}else{-1})
summary(sapply(sim_BDtrees_binary, sapply, function(x)ifelse(is.phylo(x), is.binary(x), NA)))
```

```{r}
Ntips <- sapply(sim_BDtrees_binary, sapply, function(result)if(is.numeric(result)){NA}else{length(result$tip.label)})
Ntips <- apply(Ntips, 2, as.numeric)
Ntips
```

Relabel tree tips to avoid duplicates

```{r}
new_tip_labels <- function(tree){
  tree$tip.label <- paste0("t", 1:length(tree$tip.label))
  return(tree)
}
sim_BDtrees_binary <- lapply(sim_BDtrees_binary, lapply, function(x)if(is.phylo(x)){new_tip_labels(x)}else{x})
```

```{r}
for (i in seq_along(sim_BDtrees_binary)) {
  sim_success <- sapply(sim_BDtrees_binary[[i]], is.phylo)
  if (any(sim_success)){
    write.tree(sim_BDtrees_binary[[i]][sim_success], file=paste0("shape_sim_varBD_trees/sim_varBD_pars", i, ".trees"))
  }
}
```

```{r}
trees_gammma <- sapply(sim_BDtrees_binary, sapply, function(result){
  if (is.numeric(result)){
    return(NaN)
  }else{
    return(ape::gammaStat(result))
  }
  })
trees_gammma
```

```{r}
trees_stairs2 <- sapply(sim_BDtrees_binary, sapply, function(result){
  if (is.numeric(result)){
    return(NaN)
  }else{
    return(treestats::stairs2(result))
  }
  })
trees_stairs2
```

```{r}
simul_infer <- read.csv("../PBD_bayesian_fit_CBD/8-gamma_tree_shape/12152/all_simulations_inference.csv", row.names = 1)

trees_stats <- data.frame(param_vary = simul_infer[1:(n_trees*length(full_results)), "param_vary"], 
                          i_param_var = simul_infer[1:(n_trees*length(full_results)), "i_param_var"], 
                          replicate = rep(0:(n_trees-1), each=length(full_results)),
                          gamma = as.numeric(t(trees_gammma)),
                          stairs2 = as.numeric(t(trees_stairs2)),
                          SR = as.integer(t(Ntips)))
trees_stats
write.csv(trees_stats, "shape_sim_varBD_trees/simulated_varBD_trees_stats.csv")
```




