---
title: "Compare constant-PBD simulated trees with the corresponding variable-BD simulated trees"
output: html_notebook
---

```{r}
library(reticulate)
library(castor)
```

```{r}
np <- import("numpy")
full_results <- np$load("shape_sim_varBD_trees/variable_BDrates.npy", allow_pickle=T)
params <- data.frame(apply(full_results[,5:9], 2, as.numeric))
names(params) <- c("l1","l2","l3","m1","m2")
params
```

```{r}
BD_rtt <- full_results[,10]
plot(BD_rtt[[25]][[2]])
```

## Piecewise-constant fit

```{r}
age=15
n_trees=100

sim_BDtrees <- lapply(BD_rtt, function(RTT)lapply(1:n_trees, function(i){
  generate_tree_hbds(max_tips = 10000, max_time = age, include_extant = T, include_extinct = F, time_grid = c(0, seq(0.01, age, length.out=200)[2:199]), lambda = RTT[[1]][-1], mu = RTT[[2]][-1], 0, splines_degree = 0)
  }))
```

```{r}
age=15
n_trees=100

sim_BDtrees_survival <- lapply(BD_rtt, function(RTT)lapply(1:n_trees, function(i){
  result <- generate_tree_hbds(max_tips = 10000, max_time = age, include_extant = T, include_extinct = F, time_grid = c(0, seq(0.01, age, length.out=200)[2:199]), lambda = RTT[[1]][-1], mu = RTT[[2]][-1], 0, splines_degree = 0)
  i <- 0
  while (!(result$success) && i<100){
    result <- generate_tree_hbds(max_tips = 10000, max_time = age, include_extant = T, include_extinct = F, time_grid = c(0, seq(0.01, age, length.out=200)[2:199]), lambda = RTT[[1]][-1], mu = RTT[[2]][-1], 0, splines_degree = 0)
    i <- i+1
  }
  return(result)
  }))

Ntips <- sapply(sim_BDtrees_survival, sapply, function(result)result$tree$Nnode+1)
Ntips <- apply(Ntips, 2, as.numeric)
Ntips
```

```{r}
trees_gammma <- sapply(sim_BDtrees_survival, sapply, function(result){
  tree <- result$tree
  if (is.null(tree)){
    return(NaN)
  }else{
    return(ape::gammaStat(result$tree))
  }
  })
trees_gammma
```



