---
title: "Compare constant-PBD simulated trees with the corresponding variable-BD simulated trees"
output: html_notebook
---

```{r}
library(reticulate)
library(TreeSim)
library(R.utils)
library(geiger)
library(treestats)
library(ape)
```

# Load time-varying DB rates

```{r}
np <- import("numpy")
BD_rtt <- np$load("../../simulations_output/3-varBD/variable_BDrates.npy", allow_pickle=T)
#params <- data.frame(apply(BD_rtt[,5:9], 2, as.numeric))
#names(params) <- c("l1","l2","l3","m1","m2")
#params
BD_rtt[[1]]
```

```{r}
plot(BD_rtt[[1]]$birth_rate)
plot(BD_rtt[[1]]$death_rate)
```

# Piecewise-constant simulations

```{r}
sim_tree <- function(RTT){
  #tree <- withTimeout(sim.bdsky.stt(n           = 0,
  #                                 timestop    = age,
  #                                 lambdasky   = RTT$birth_rate,
  #                                 deathsky    = RTT$death_rate,
  #                                 timesky     = seq(0.0, age, length.out=200),
  #                                 sampprobsky = rep(0,200),
  #                                 rho         = 1), timeout = 60.0, onTimeout = "warning")
   tree <- sim.bdsky.stt(n           = 0,
                         timestop    = age,
                         lambdasky   = RTT$birth_rate,
                         deathsky    = RTT$death_rate,
                         timesky     = seq(0.0, age, length.out=200),
                         sampprobsky = rep(0,200),
                         rho         = 1)
  
  # Single tip
  if (is.numeric(tree) && tree == age){
    #branch <- list(edge =  matrix(c(2, 1), ncol = 2), edge.length = age, tip.label = "t1", Nnode = 1, root.edge = 0)
    #class(branch) <- "phylo"
    #return(branch)
    return(-1)
  }
  
  return(tree[[1]])
}

age=15
n_trees  = 500
n_trials = 100

## Crown simulations
# sim_BDtrees <- lapply(BD_rtt, function(RTT)lapply(1:n_trees, function(i){
#   i <- 0
#   while (i<10){
#     #print(paste("i=", i))
#     tree_left <- sim_tree(RTT)
#     if (is.phylo(tree_left)){
#       tree_right <- sim_tree(RTT)
#       if (is.phylo(tree_right)){
#         return(bind.tree(tree_left, tree_right, position=tree_left$root.edge))
#       }
#     }
#     i <- i+1
#   }
#   return(-1)
# }))

## Stem simulations
sim_BDtrees <- lapply(BD_rtt, function(RTT)lapply(1:n_trees, function(i){
  if (mean(RTT$birth_rate - RTT$death_rate) > log(10000)/age) return(-1) ## Remove trees whose expected size is too large
  i <- 0
  while (i<n_trials){
    #print(paste("i=", i))
    tree <- sim_tree(RTT)
    if (is.phylo(tree)){
      return(tree)
    }
    i <- i+1
  }
  return(-1)
}))
```

```{r warning = FALSE, message=FALSE}
# sim_BDtrees_summary <- summary(sapply(sim_BDtrees, sapply, function(x)ifelse(is.phylo(x), length(x$tip.label) == 1 || is.binary.tree(x), NA)))
# sim_BDtrees_summary
# 
# make.binary <- function(tree){
#   while (!is.binary.tree(tree)){
#     i_max_1 <- which.max(tree$edge[,1])
#     i_max_2 <- which.max(tree$edge[,2])
#     tree$edge <- cbind(tree$edge[-i_max_1,1], tree$edge[-i_max_2,2])
#     tree$Nnode <- tree$Nnode - 1
#     len = length(tree$edge.length)
#     if (i_max_2==1){
#       tree$edge.length <- c(tree$edge.length[1]+tree$edge.length[2], tree$edge.length[3:len])
#     }else if (i_max_2 == len-1){
#       tree$edge.length <- c(tree$edge.length[1:(i_max_2-1)], tree$edge.length[i_max_2]+tree$edge.length[i_max_2+1])
#     }else{
#       tree$edge.length <- c(tree$edge.length[1:(i_max_2-1)], tree$edge.length[i_max_2]+tree$edge.length[i_max_2+1], tree$edge.length[(i_max_2+2):length(tree$edge.length)])
#     }
#   }
#   return(tree)
# }
# sim_BDtrees_binary <- lapply(sim_BDtrees, lapply, function(x)if(is.phylo(x)){if(length(x$tip.label)==1){x}else{make.binary(x)}}else{-1})
sim_BDtrees_binary <- sim_BDtrees
summary(sapply(sim_BDtrees_binary, sapply, function(x)ifelse(is.phylo(x), length(x$tip.label) == 1 || is.binary(x), NA)))
```

```{r}
Ntips <- sapply(sim_BDtrees_binary, sapply, function(result)if(is.numeric(result)){NA}else{length(result$tip.label)})
Ntips
```

```{r}
for (i in seq_along(sim_BDtrees_binary)) {
  sim_success <- sapply(sim_BDtrees_binary[[i]], is.phylo)
  if (any(sim_success)){
    write.tree(sim_BDtrees_binary[[i]][sim_success], file=paste0("../../simulations_output/3-varBD/trees/sim_varBD_pars", i, ".trees"))
  }
}
```

```{r}
# Function to reload saved trees
reload_sim_BDtrees <- function(path, num_pars, n_trees) {
  sim_BDtrees_binary <- vector("list", num_pars)
  
  for (i in seq_len(num_pars)) {
    file_path <- file.path(path, paste0("sim_varBD_pars", i, ".trees"))
    if (file.exists(file_path)) {
      trees <- read.tree(file_path)
      trees <- lapply(trees, identity)  # Ensure trees is a list even if there's only one tree in the file
      
      # Fill the list up to n_trees with -1 if necessary
      sim_BDtrees_binary[[i]] <- c(trees, rep(list(-1), n_trees - length(trees)))
    } else {
      # If file doesn't exist, fill with -1
      sim_BDtrees_binary[[i]] <- rep(list(-1), n_trees)
    }
  }
  
  return(sim_BDtrees_binary)
}

sim_BDtrees_binary <- reload_sim_BDtrees("../../simulations_output/3-varBD/trees", nrow(BD_rtt), n_trees)
```

```{r warning=FALSE}
trees_gammma <- sapply(sim_BDtrees_binary, sapply, function(result){
  if (is.numeric(result)){
    return(NaN)
  }else{
    return(ape::gammaStat(result))
  }
  })
trees_gammma
```

```{r}
trees_stairs2 <- sapply(sim_BDtrees_binary, sapply, function(result){
  if (is.numeric(result)){
    return(NaN)
  }else{
    return(treestats::stairs2(result))
  }
  })
trees_stairs2
```

```{r warning=FALSE}
trees_beta <- sapply(sim_BDtrees_binary, sapply, function(result){
  if (is.numeric(result)){
    return(NaN)
  }else{
    return(treestats::beta_statistic(result))
  }
  })
trees_beta
```

```{r}
simul_infer <- read.csv("../../simulations_output/1-PBD/all_simulations_inference.csv", row.names = 1)

trees_stats <- data.frame(param_vary = rep(rep(1:5, each=5), n_trees), 
                          i_param_var = rep(1:5, n_trees), 
                          replicate = rep(0:(n_trees-1), each=length(BD_rtt)),
                          gamma = as.numeric(t(trees_gammma)),
                          stairs2 = as.numeric(t(trees_stairs2)),
                          beta = as.numeric(t(trees_beta)),
                          SR = as.integer(t(Ntips)))
trees_stats
write.csv(trees_stats, "../../simulations_output/3-varBD/simulated_varBD_trees_stats.csv")
```




